In [1]:
import numpy as np
import pandas as pd

In [2]:
!dir

 Volume in drive C has no label.
 Volume Serial Number is 36E8-2B7A

 Directory of C:\Users\user

09/07/2026  11:02 AM    <DIR>          .
04/23/2026  12:00 AM    <DIR>          ..
08/31/2026  02:42 PM    <DIR>          .cache
08/31/2026  10:48 AM                65 .gitconfig
09/07/2026  10:40 AM    <DIR>          .ipynb_checkpoints
08/12/2026  12:22 PM    <DIR>          .ipython
08/12/2026  12:29 PM    <DIR>          .jupyter
08/18/2026  01:29 PM               647 011.txt
09/02/2026  11:46 AM    <DIR>          4IK25CS045
08/31/2026  10:28 AM    <DIR>          4IK25CS077 DAV
08/31/2026  10:21 AM             2,931 4IK25CS077.ipynb
08/19/2026  10:33 AM    <DIR>          Akash
09/04/2026  04:21 PM    <DIR>          Ananta_DAV21
04/23/2026  12:00 AM    <DIR>          Contacts
08/31/2026  10:28 AM    <DIR>          DAV
09/02/2026  01:04 PM    <DIR>          Desktop
06/03/2026  02:23 PM    <DIR>          Documents
09/07/2026  09:45 AM    <DIR>          Downloads
04/23/2026  12:00 AM    <DIR>          Favorites
09/07/2026  09:46 AM    <DIR>          Gowtham SD
09/07/2026  11:02 AM            50,857 GowthamSDJ2.ipynb
08/18/2026  04:22 PM    <DIR>          hudha
09/01/2026  04:26 PM    <DIR>          lakshmi
04/23/2026  12:00 AM    <DIR>          Links
04/23/2026  12:00 AM    <DIR>          Music
04/23/2026  12:01 AM    <DIR>          OneDrive
09/02/2026  03:06 PM             2,521 p1.ipynb
09/04/2026  04:17 PM    <DIR>          Pictures
09/02/2026  10:34 AM            13,106 Program-2(4NI25CI100).ipynb
04/23/2026  12:00 AM    <DIR>          Saved Games
04/22/2026  12:25 PM    <DIR>          Searches
09/02/2026  12:01 PM               266 student.csv
09/07/2026  09:45 AM            72,036 StudentsPerformance.csv
09/02/2026  12:09 PM             4,619 studentt 1.ipynb
08/19/2026  12:14 PM                72 Untitled.ipynb
08/14/2026  03:17 PM                 0 untitled.py
08/17/2026  10:29 AM                 0 untitled.txt
08/19/2026  04:21 PM             1,302 Untitled1.ipynb
08/14/2026  03:17 PM                 0 untitled1.py
08/31/2026  09:18 AM               337 Untitled2.ipynb
08/31/2026  09:17 AM                 0 untitled2.py
09/02/2026  12:43 PM            11,181 Untitled3.ipynb
09/02/2026  12:56 PM             2,748 Untitled4.ipynb
05/04/2026  11:39 AM    <DIR>          Videos
              18 File(s)        162,688 bytes
              26 Dir(s)  177,112,039,424 bytes free

In [3]:
df=pd.read_csv("StudentsPerformance.csv")

In [4]:
print(df)

     gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard
1    female        group C                some college      standard
2    female        group B             master's degree      standard
3      male        group A          associate's degree  free/reduced
4      male        group C                some college      standard
..      ...            ...                         ...           ...
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
0                      none          72             72             74
1                 completed          69             90             88
2                      none          90             95             93
3                      none          47             57             44
4                      none          76             78             75
..                      ...         ...            ...            ...
995               completed          88             99             95
996                    none          62             55             55
997               completed          59             71             65
998               completed          68             78             77
999                    none          77             86             86

[1000 rows x 8 columns]

In [5]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [6]:
df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [7]:
df.shape

(1000, 8)

In [8]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='str')

In [9]:
df.dtypes

gender                           str
race/ethnicity                   str
parental level of education      str
lunch                            str
test preparation course          str
math score                     int64
reading score                  int64
writing score                  int64
dtype: object

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race/ethnicity               1000 non-null   str
 2   parental level of education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 62.6 KB

In [11]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [12]:
print(df["math score"].mean())

66.089

In [13]:
print(df["math score"].median())

66.0

In [14]:
print(df["math score"].mode())

0    65
Name: math score, dtype: int64

In [15]:
print(df["math score"].var())

229.91899799799796

In [16]:
print(df["math score"].std())

15.16308009600945

In [17]:
print(df["math score"].min())

0

In [18]:
print(df["math score"].max())

100

In [19]:
print(df["math score"].count())

1000

In [20]:
print(df["gender"].unique())

<StringArray>
['female', 'male']
Length: 2, dtype: str

In [21]:
print(df["gender"].nunique())

2

In [22]:
print(df["gender"].value_counts())

gender
female    518
male      482
Name: count, dtype: int64

In [23]:
print(df.isnull())

     gender  race/ethnicity  parental level of education  lunch  \
0     False           False                        False  False
1     False           False                        False  False
2     False           False                        False  False
3     False           False                        False  False
4     False           False                        False  False
..      ...             ...                          ...    ...
995   False           False                        False  False
996   False           False                        False  False
997   False           False                        False  False
998   False           False                        False  False
999   False           False                        False  False

     test preparation course  math score  reading score  writing score
0                      False       False          False          False
1                      False       False          False          False
2                      False       False          False          False
3                      False       False          False          False
4                      False       False          False          False
..                       ...         ...            ...            ...
995                    False       False          False          False
996                    False       False          False          False
997                    False       False          False          False
998                    False       False          False          False
999                    False       False          False          False

[1000 rows x 8 columns]

In [24]:
print(df.isnull().sum())

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [25]:
print(df.isnull().mean()*100)

gender                         0.0
race/ethnicity                 0.0
parental level of education    0.0
lunch                          0.0
test preparation course        0.0
math score                     0.0
reading score                  0.0
writing score                  0.0
dtype: float64

In [26]:
print(df.dropna)

<bound method DataFrame.dropna of      gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard
1    female        group C                some college      standard
2    female        group B             master's degree      standard
3      male        group A          associate's degree  free/reduced
4      male        group C                some college      standard
..      ...            ...                         ...           ...
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
0                      none          72             72             74
1                 completed          69             90             88
2                      none          90             95             93
3                      none          47             57             44
4                      none          76             78             75
..                      ...         ...            ...            ...
995               completed          88             99             95
996                    none          62             55             55
997               completed          59             71             65
998               completed          68             78             77
999                    none          77             86             86

[1000 rows x 8 columns]>

In [27]:
print(df.fillna(0))

     gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard
1    female        group C                some college      standard
2    female        group B             master's degree      standard
3      male        group A          associate's degree  free/reduced
4      male        group C                some college      standard
..      ...            ...                         ...           ...
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
0                      none          72             72             74
1                 completed          69             90             88
2                      none          90             95             93
3                      none          47             57             44
4                      none          76             78             75
..                      ...         ...            ...            ...
995               completed          88             99             95
996                    none          62             55             55
997               completed          59             71             65
998               completed          68             78             77
999                    none          77             86             86

[1000 rows x 8 columns]

In [28]:
print(df.duplicated())

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [29]:
print(df.duplicated().sum())

0

In [30]:
print(df.drop_duplicates())

     gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard
1    female        group C                some college      standard
2    female        group B             master's degree      standard
3      male        group A          associate's degree  free/reduced
4      male        group C                some college      standard
..      ...            ...                         ...           ...
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
0                      none          72             72             74
1                 completed          69             90             88
2                      none          90             95             93
3                      none          47             57             44
4                      none          76             78             75
..                      ...         ...            ...            ...
995               completed          88             99             95
996                    none          62             55             55
997               completed          59             71             65
998               completed          68             78             77
999                    none          77             86             86

[1000 rows x 8 columns]

In [31]:
print(df["lunch"])

0          standard
1          standard
2          standard
3      free/reduced
4          standard
           ...
995        standard
996    free/reduced
997    free/reduced
998        standard
999    free/reduced
Name: lunch, Length: 1000, dtype: str

In [32]:
print(df[["lunch","test preparation course"]])

            lunch test preparation course
0        standard                    none
1        standard               completed
2        standard                    none
3    free/reduced                    none
4        standard                    none
..            ...                     ...
995      standard               completed
996  free/reduced                    none
997  free/reduced               completed
998      standard               completed
999  free/reduced                    none

[1000 rows x 2 columns]

In [33]:
print(df.iloc[0:5])

   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard

  test preparation course  math score  reading score  writing score
0                    none          72             72             74
1               completed          69             90             88
2                    none          90             95             93
3                    none          47             57             44
4                    none          76             78             75

In [34]:
print(df[df["math score"]>75])

     gender race/ethnicity parental level of education         lunch  \
2    female        group B             master's degree      standard
4      male        group C                some college      standard
6    female        group B                some college      standard
13     male        group A                some college      standard
16     male        group C                 high school      standard
..      ...            ...                         ...           ...
983  female        group A                some college      standard
987    male        group E            some high school      standard
990    male        group E                 high school  free/reduced
995  female        group E             master's degree      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
2                      none          90             95             93
4                      none          76             78             75
6                 completed          88             95             92
13                completed          78             72             70
16                     none          88             89             86
..                      ...         ...            ...            ...
983               completed          78             87             91
987               completed          81             75             76
990               completed          86             81             75
995               completed          88             99             95
999                    none          77             86             86

[274 rows x 8 columns]

In [35]:
print(df.sort_values("math score"))

     gender race/ethnicity parental level of education         lunch  \
59   female        group C            some high school  free/reduced
980  female        group B                 high school  free/reduced
17   female        group B            some high school  free/reduced
787  female        group B                some college      standard
145  female        group C                some college  free/reduced
..      ...            ...                         ...           ...
623    male        group A                some college      standard
625    male        group D                some college      standard
962  female        group E          associate's degree      standard
458  female        group E           bachelor's degree      standard
916    male        group E           bachelor's degree      standard

    test preparation course  math score  reading score  writing score
59                     none           0             17             10
980                    none           8             24             23
17                     none          18             32             28
787                    none          19             38             32
145                    none          22             39             33
..                      ...         ...            ...            ...
623               completed         100             96             86
625               completed         100             97             99
962                    none         100            100            100
458                    none         100            100            100
916               completed         100            100            100

[1000 rows x 8 columns]

In [36]:
print(df.rename(columns={"gender":"genders"}))

    genders race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard
1    female        group C                some college      standard
2    female        group B             master's degree      standard
3      male        group A          associate's degree  free/reduced
4      male        group C                some college      standard
..      ...            ...                         ...           ...
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
0                      none          72             72             74
1                 completed          69             90             88
2                      none          90             95             93
3                      none          47             57             44
4                      none          76             78             75
..                      ...         ...            ...            ...
995               completed          88             99             95
996                    none          62             55             55
997               completed          59             71             65
998               completed          68             78             77
999                    none          77             86             86

[1000 rows x 8 columns]

In [37]:
df["math scores"] = df["writing score"]*0.10

In [38]:
print(df.drop("math scores",axis=1))

     gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard
1    female        group C                some college      standard
2    female        group B             master's degree      standard
3      male        group A          associate's degree  free/reduced
4      male        group C                some college      standard
..      ...            ...                         ...           ...
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
0                      none          72             72             74
1                 completed          69             90             88
2                      none          90             95             93
3                      none          47             57             44
4                      none          76             78             75
..                      ...         ...            ...            ...
995               completed          88             99             95
996                    none          62             55             55
997               completed          59             71             65
998               completed          68             78             77
999                    none          77             86             86

[1000 rows x 8 columns]

In [39]:
print(df.groupby("gender"))

<pandas.api.typing.DataFrameGroupBy object at 0x000002AB0F246CF0>

In [40]:
print(df.groupby("gender")
      ["math score"].mean())

gender
female    63.633205
male      68.728216
Name: math score, dtype: float64

In [41]:
pd.concat([df1,df2])

NameError: name 'df1' is not defined

In [42]:
print(pd.merge(df1,df2,on="lunch"))

NameError: name 'df1' is not defined

In [43]:
!git init

Reinitialized existing Git repository in C:/Users/user/.git/

In [45]:
!git config user.name "Gowtham S D"

In [46]:
!git config user.email "2025cs_gowthamsd_c@nie.ac.in"

In [47]:
!git remote add origin https://github.com/gowthamsd7/DAV-lab.git